// Regenerates icons.js from node_modules so slides.html needs no network or npm at render time.
// Line icons: Lucide (ISC). Brand glyphs: Simple Icons (CC0; the logos themselves stay their owners' trademarks).
import { readFileSync, writeFileSync } from 'node:fs';

const LINE = [
  'shield-check', 'clipboard-list', 'square-terminal', 'scan-eye', 'file-pen-line', 'scale',
  'landmark', 'mic', 'messages-square', 'radar', 'calendar-days', 'arrow-right', 'bug', 'shield',
  'git-fork', 'scissors', 'flask-conical', 'wrench', 'coins', 'refresh-ccw', 'user-round', 'cloud',
  'calendar-clock', 'database', 'lock', 'quote', 'mail',
];
const BRAND = [
  'gmail', 'googlecalendar', 'googledrive', 'notion', 'calendly', 'fathom', 'github', 'supabase',
  'docker', 'terraform', 'postgresql', 'ollama', 'youtube', 'canva',
];

const inner = (svg) => svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>[\s\S]*?<\/title>/, '').trim();

const line = Object.fromEntries(LINE.map((n) => [n, inner(readFileSync(`node_modules/lucide-static/icons/${n}.svg`, 'utf8'))]));
const brand = Object.fromEntries(BRAND.map((n) => [n, inner(readFileSync(`node_modules/simple-icons/icons/${n}.svg`, 'utf8'))]));

writeFileSync('icons.js', `// Generated by build-icons.mjs. Do not edit by hand.\nwindow.ICONS = ${JSON.stringify({ line, brand }, null, 1)};\n`);
console.log(`icons.js: ${LINE.length} line icons, ${BRAND.length} brand glyphs`);
