// All carousel copy lives here. Edit text in this file, then run `npm run render`.
// `status` is for review only and never renders: 'verified' = backed by your README or public
// repos; 'confirm' = inferred from the tools connected to your Claude account, check it's true.
window.HANDLE = '@shareefico';

window.SLIDES = [
  {
    type: 'cover',
    eyebrow: 'Itqan Studio · Dubai',
    title: ['My week', 'with Claude'], // first word of the second line is set in italic
    sub: 'How I run a B2B web and AI studio, one workflow at a time.',
  },
  {
    type: 'overview',
    eyebrow: 'My week with Claude',
    title: 'The week at a glance',
  },
  {
    type: 'day', key: 'plan', status: 'confirm',
    day: 'SUN', n: '01', band: 'sky', icon: 'clipboard-list',
    when: 'Sunday, 8:00pm', title: 'Plan the week',
    what: "One page: what's due, and what needs me.",
    body: "Claude reads my calendar and inbox, then writes one page: what's due, who's waiting on me, and the three things only I can do.",
    ask: 'plan my week',
    tools: [['brand', 'gmail', 'Gmail'], ['brand', 'googlecalendar', 'Google Calendar'], ['brand', 'notion', 'Notion']],
  },
  {
    type: 'day', key: 'build', status: 'verified',
    day: 'MON', n: '02', band: 'clay', icon: 'square-terminal',
    when: 'Monday, 9:00am', title: 'Build in Claude Code',
    what: 'Client sites, the CRM and its iOS app.',
    body: 'Where most of my day happens. Client sites, the Itqan CRM and its iOS app. I describe the outcome, Claude writes the code, I read every diff.',
    ask: 'add a Face ID lock to the app',
    tools: [['brand', 'github', 'GitHub'], ['brand', 'supabase', 'Supabase'], ['brand', 'docker', 'Docker'], ['brand', 'terraform', 'Terraform']],
  },
  {
    type: 'day', key: 'panel', status: 'verified',
    day: 'MON', n: '03', band: 'heather', icon: 'scan-eye',
    when: 'Before every merge', title: 'The Panel reviews it',
    what: 'Five outside models. Fails closed.',
    body: "Five models from four vendors review every change, one lens each, and Claude only synthesizes. Claude reviewing Claude's code misses Claude-shaped bugs.",
    note: { label: 'Fails closed', icon: 'lock', text: 'If a blocking seat dies, the verdict is INCONCLUSIVE, never a pass.' },
    ask: 'have the panel review this', cmd: '/panel',
    toolsLabel: 'The seats',
    tools: [['line', 'bug', 'Codex'], ['line', 'shield', 'Qwen'], ['line', 'git-fork', 'DeepSeek'], ['line', 'scissors', 'GLM'], ['line', 'flask-conical', 'Kimi']],
  },
  {
    type: 'day', key: 'proposal', status: 'confirm',
    day: 'TUE', n: '04', band: 'olive', icon: 'file-pen-line',
    when: 'Tuesday', title: 'Calls become proposals',
    what: 'Call notes in, scoped proposal out.',
    body: "Discovery calls are recorded with consent. Claude turns the notes and our past projects into a scoped proposal. Nothing goes out until I've edited it.",
    ask: 'turn this call into a proposal',
    tools: [['brand', 'calendly', 'Calendly'], ['brand', 'fathom', 'Fathom'], ['brand', 'googledrive', 'Google Drive'], ['brand', 'gmail', 'Gmail']],
  },
  {
    type: 'day', key: 'tax', status: 'verified',
    day: 'WED', n: '05', band: 'oat', icon: 'scale',
    when: 'Wednesday', title: 'Tax questions get citations',
    what: 'The verbatim law, or nothing.',
    body: 'Markaz, my MCP server over UAE tax law, returns the verbatim article with its citation, or nothing. Anything unverified gets flagged.',
    ask: 'cite the e-invoicing rules', cmd: 'get_provision', cmdLabel: 'or call',
    tools: [['line', 'landmark', 'FTA legislation'], ['brand', 'postgresql', 'PostgreSQL'], ['brand', 'ollama', 'Ollama']],
    fine: 'A retrieval tool, not tax advice. Always verify against the FTA’s own text.',
  },
  {
    type: 'day', key: 'content', status: 'confirm',
    day: 'THU', n: '06', band: 'blush', icon: 'mic',
    when: 'Thursday', title: 'One episode, a week of content',
    what: 'Clips, posts and a newsletter.',
    body: 'Every Barakah Blueprint episode becomes clips, posts and a newsletter, drafted in my voice and staged for my OK.',
    ask: "cut this episode into next week's posts",
    tools: [['brand', 'youtube', 'YouTube'], ['line', 'mail', 'Kit'], ['brand', 'canva', 'Canva'], ['line', 'calendar-clock', 'Metricool']],
  },
  {
    type: 'day', key: 'board', status: 'verified',
    day: 'FRI', n: '07', band: 'heather', icon: 'messages-square',
    when: 'Friday', title: 'Big calls go to the board',
    what: 'Four blind advisors who disagree.',
    body: "Four advisors answer in sealed sessions, blind to each other, and they're built to disagree. When they split, I've found the real decision.",
    ask: 'build it for them, or say no?', cmd: '/board',
    toolsLabel: 'The seats',
    tools: [['line', 'wrench', 'The Operator'], ['line', 'coins', 'The Capital Allocator'], ['line', 'refresh-ccw', 'The Contrarian'], ['line', 'user-round', 'The Customer']],
  },
  {
    type: 'day', key: 'absence', status: 'confirm',
    day: 'END', n: '08', band: 'sky', icon: 'radar',
    when: 'Month end', title: 'Check the absences',
    what: 'Every status nobody watches.',
    body: 'I once found a backup policy that had sat in ERROR for 45 days. Broken looked exactly like working. Now Claude reads every status nobody watches.',
    ask: "what's failing quietly?",
    tools: [['line', 'cloud', 'AWS'], ['brand', 'terraform', 'Terraform'], ['brand', 'supabase', 'Supabase']],
  },
  {
    type: 'closing', status: 'confirm',
    label: 'You stay in charge',
    title: ['Claude drafts.', 'I decide.'],
    body: 'Nothing sends, merges, posts or pays without my OK. That part of the week stays mine.',
    arabic: 'إتقان',
    itqan: 'Itqan: doing something with the precision it deserves.',
    cta: 'Follow @shareefico',
    ctaText: 'for how each day is built',
    foot: 'Itqan Studio · B2B web & AI · Dubai',
  },
];
